// AUTO-GENERATED from TBIM_Interactive_Map_Database_Template.xlsx by excel_to_data.py
// Edit the Excel file, then run:  python3 excel_to_data.py
window.TBIM_DATA = {
  "event": {
    "name": "BIM Bootcamp 2026",
    "date": "9 October 2026",
    "venue": "Sripatum University (SPU)",
    "floor": "1F",
    "floorplan": "assets/floorplan_clean.png"
  },
  "booths": [
    {
      "id": "J1",
      "name": "Thai Obayashi",
      "category": "Job Fair",
      "x": 43.49,
      "y": 29.59,
      "w": 4.49,
      "h": 6.54,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/J1.svg",
      "note": ""
    },
    {
      "id": "J2",
      "name": "Christiani & Nielsen",
      "category": "Job Fair",
      "x": 48.11,
      "y": 29.59,
      "w": 4.56,
      "h": 6.54,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/J2.png",
      "note": ""
    },
    {
      "id": "J3",
      "name": "STECON",
      "category": "Job Fair",
      "x": 52.86,
      "y": 29.59,
      "w": 4.49,
      "h": 6.54,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/J3.png",
      "note": ""
    },
    {
      "id": "J4",
      "name": "Syntec",
      "category": "Job Fair",
      "x": 58.72,
      "y": 29.59,
      "w": 4.88,
      "h": 6.54,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/excel/J4.png",
      "note": ""
    },
    {
      "id": "J5",
      "name": "Bimspaces",
      "category": "Job Fair",
      "x": 58.72,
      "y": 36.13,
      "w": 5.08,
      "h": 7.52,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/excel/J5.png",
      "note": ""
    },
    {
      "id": "J6",
      "name": "Solumat",
      "category": "Job Fair",
      "x": 52.86,
      "y": 36.13,
      "w": 4.49,
      "h": 7.52,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/J6.png",
      "note": ""
    },
    {
      "id": "J7",
      "name": "Innoplan x JAI Group x Wisdom",
      "category": "Job Fair",
      "x": 48.05,
      "y": 36.13,
      "w": 4.62,
      "h": 7.52,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/J7.png",
      "note": ""
    },
    {
      "id": "J8",
      "name": "Ritta",
      "category": "Job Fair",
      "x": 43.23,
      "y": 36.13,
      "w": 4.75,
      "h": 7.52,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/J8.png",
      "note": ""
    },
    {
      "id": "P1",
      "name": "Berger",
      "category": "Partnership",
      "x": 35.29,
      "y": 12.21,
      "w": 4.82,
      "h": 6.05,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/P1.jpg",
      "note": ""
    },
    {
      "id": "P2",
      "name": "Sustainable Solution",
      "category": "Partnership",
      "x": 40.1,
      "y": 12.21,
      "w": 5.27,
      "h": 6.05,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/P2.png",
      "note": ""
    },
    {
      "id": "P3",
      "name": "DELL",
      "category": "Partnership",
      "x": 45.38,
      "y": 12.21,
      "w": 4.56,
      "h": 6.05,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/P3.svg",
      "note": ""
    },
    {
      "id": "P4",
      "name": "SYNNEX",
      "category": "Partnership",
      "x": 49.93,
      "y": 12.21,
      "w": 5.4,
      "h": 6.05,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/P4.png",
      "note": ""
    },
    {
      "id": "P5",
      "name": "Autodesk",
      "category": "Partnership",
      "x": 55.34,
      "y": 12.21,
      "w": 9.11,
      "h": 6.05,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/P5.png",
      "note": ""
    },
    {
      "id": "P6",
      "name": "SynergySoft",
      "category": "Partnership",
      "x": 64.45,
      "y": 12.21,
      "w": 4.88,
      "h": 6.05,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/P6.png",
      "note": ""
    },
    {
      "id": "P7",
      "name": "Digitech One",
      "category": "Partnership",
      "x": 69.34,
      "y": 12.21,
      "w": 9.83,
      "h": 6.05,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/P7.png",
      "note": ""
    },
    {
      "id": "P8",
      "name": "BSI",
      "category": "Partnership",
      "x": 33.85,
      "y": 21.48,
      "w": 3.78,
      "h": 7.62,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/P8.svg",
      "note": ""
    },
    {
      "id": "REG",
      "name": "Registration",
      "category": "Facility",
      "x": 29.1,
      "y": 32.1,
      "w": 8.53,
      "h": 6.05,
      "rot": -18,
      "poly": null,
      "description": "Registration desk; 2 staff standby. T-shirt distribution after registration.",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/REG.png",
      "note": "2 desks / 4 seats"
    },
    {
      "id": "ADV",
      "name": "Hardware Zone (ADVICE)",
      "category": "Facility",
      "x": 6.84,
      "y": 59.77,
      "w": 34.05,
      "h": 19.14,
      "rot": 0,
      "poly": [
        [
          9.77,
          62.01
        ],
        [
          12.7,
          68.85
        ],
        [
          15.3,
          73.73
        ],
        [
          17.58,
          74.8
        ],
        [
          26.69,
          74.8
        ],
        [
          32.55,
          73.73
        ],
        [
          37.11,
          71.78
        ],
        [
          40.82,
          63.48
        ],
        [
          38.09,
          59.96
        ],
        [
          35.16,
          65.43
        ],
        [
          31.58,
          68.95
        ],
        [
          27.02,
          70.21
        ],
        [
          17.25,
          69.43
        ],
        [
          15.62,
          65.92
        ],
        [
          12.7,
          59.47
        ]
      ],
      "description": "Hardware Booth",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/ADV.png",
      "note": "Advice zone 2.5x2m"
    },
    {
      "id": "ENT",
      "name": "Main Entrance",
      "category": "Facility",
      "x": 33.2,
      "y": 79.3,
      "w": 15.95,
      "h": 6.35,
      "rot": 0,
      "poly": null,
      "description": "Main entrance to the event floor.",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "",
      "note": "Future: link directions to training rooms"
    },
    {
      "id": "YBIM",
      "name": "Young BIM Club",
      "category": "Facility",
      "x": 18.55,
      "y": 43.95,
      "w": 3.45,
      "h": 6.45,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "assets/logos/YBIM.png",
      "note": "2 desks / 4 seats"
    },
    {
      "id": "BRK",
      "name": "Break",
      "category": "Facility",
      "x": 77.86,
      "y": 30.47,
      "w": 1.95,
      "h": 5.86,
      "rot": 0,
      "poly": null,
      "description": "",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "",
      "note": "Break area"
    },
    {
      "id": "TR1",
      "name": "Training Room 1",
      "category": "Facility",
      "x": null,
      "y": null,
      "w": null,
      "h": null,
      "rot": 0,
      "poly": null,
      "description": "Training area · 86 seats · 43 desks · speaker 1 desk + 2 seats",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "",
      "note": "Right-hand 1F plan (floorplan_right.png)"
    },
    {
      "id": "RESC",
      "name": "Right escalator",
      "category": "Facility",
      "x": null,
      "y": null,
      "w": null,
      "h": null,
      "rot": 0,
      "poly": null,
      "description": "Right escalator up to 2F → Training Room 2",
      "products": "",
      "contact": "",
      "phone": "",
      "website": "",
      "qr": "",
      "logo": "",
      "note": "Right-hand 1F plan (floorplan_right.png)"
    }
  ],
  "rooms": [
    {
      "id": "TR1",
      "name": "Training Room 1",
      "pathway": "Pathway 1: AEC - Design & Construction",
      "floor": "1F",
      "x": null,
      "y": null,
      "w": null,
      "h": null
    },
    {
      "id": "TR3",
      "name": "Training Room 3",
      "pathway": "Pathway 2: Project Management",
      "floor": "3F",
      "x": null,
      "y": null,
      "w": null,
      "h": null
    },
    {
      "id": "TR2",
      "name": "Training Room 2",
      "pathway": "Pathway 3: Organisation Digital Practice",
      "floor": "2F",
      "x": null,
      "y": null,
      "w": null,
      "h": null
    },
    {
      "id": "EX1",
      "name": "Executive Session",
      "pathway": "",
      "floor": "14F",
      "x": null,
      "y": null,
      "w": null,
      "h": null
    }
  ],
  "classes": [
    {
      "id": "C01",
      "room": "TR1",
      "start": "09:00",
      "end": "10:00",
      "topic": "Collaboration process through BIM for Suan Dusit Arun Park",
      "speaker": "Paponpat Chotipanpat",
      "org": "Landscape Collaboration",
      "takeaway": "การบูรณาการ (integration) ระหว่างงานออกแบบสถาปัตยกรรม ภูมิสถาปัตยกรรม การก่อสร้าง และการบริหารงานโครงการด้วย digital technology และระบบ BIM ผ่านตัวอย่างงานออกแบบสวนดุสิตอรุณ โครงการ Dusit Central Park"
    },
    {
      "id": "C02",
      "room": "TR1",
      "start": "10:20",
      "end": "11:20",
      "topic": "Talk to Your Revit Model through an AI Agent",
      "speaker": "พี่เบน",
      "org": "A49",
      "takeaway": "มาดูกันว่า AI จะเปลี่ยน Revit จากแค่โปรแกรมที่คุณใช้งาน ให้กลายเป็นโมเดลที่คุณสามารถพูดคุยด้วยได้อย่างไร ช่วยจัดการงานต่างๆ แบบอัตโนมัติ วิเคราะห์ข้อมูล และคืนเวลาให้ดีไซเนอร์ได้โฟกัสกับงานออกแบบอย่างเต็มที่ พร้อมร่วมมองไปสู่อนาคตที่ AI จะไม่เพียงแค่รับคำสั่งในการออกแบบ แต่ยังช่วยคาดการณ์ผลกระทบที่อาจเกิดขึ้นได้อีกด้วย"
    },
    {
      "id": "C03",
      "room": "TR1",
      "start": "11:20",
      "end": "12:20",
      "topic": "Hey Revit, do this!!! – BIM Automation with MCP",
      "speaker": "Penthai na Pombejra",
      "org": "Meinhardt",
      "takeaway": "Session นี้จะนำเสนอการใช้ MCP เชื่อม AI Agent เข้ากับ Revit และเครื่องมือ BIM เพื่อให้ AI สามารถอ่านข้อมูล สั่งงาน และทำงานกับ BIM Model ผ่าน Workflow ที่เป็นระบบ ตั้งแต่การตรวจสอบและดึงข้อมูล การแก้ไขข้อมูล งานซ้ำ ๆ ไปจนถึง Multi-step Automation ที่ AI สามารถวิเคราะห์ เลือก Action ดำเนินการ และตรวจสอบผลลัพธ์ได้\nเนื้อหาจะครอบคลุมแนวทางออกแบบ MCP Tool, Prompt Logic และ Automation Logic ให้ทำงานร่วมกันอย่างมีประสิทธิภาพ โดยลด Context และ Token ที่ไม่จำเป็น เลือกระดับของ Tool ให้เหมาะสม และกำหนดให้ชัดเจนว่างานส่วนใดควรให้ AI วิเคราะห์และตัดสินใจ, ส่วนใดควรใช้ Script / API แบบตายตัว และส่วนใดควรมี Human Approval หรือ Validation ก่อนแก้ไขโมเดล\nนอกจากนี้จะมองต่อไปถึงศักยภาพของ MCP + AI ในงาน BIM Automation ทั้งการเชื่อมหลายโปรแกรม หลายแหล่งข้อมูล และระบบภายนอก พร้อมตัวอย่าง Use Case สำหรับงาน BIM Production เพื่อให้เห็นว่า MCP เหมาะกับงานลักษณะใด และกรณีใดควรเลือกใช้ Automation รูปแบบอื่นแทน"
    },
    {
      "id": "C04",
      "room": "TR1",
      "start": "13:30",
      "end": "15:00",
      "topic": "AI Agent for SketchUp",
      "speaker": "อ. ป้อม (Sutipong Songkran)",
      "org": "Digitech One",
      "takeaway": "ใช้ AI Agent และภาษาธรรมชาติสร้างหรือแก้โมเดล SketchUp แบบ Real-time รวมถึงพัฒนา SketchUp Extension และเครื่องมือ BIM เฉพาะงาน"
    },
    {
      "id": "C05",
      "room": "TR1",
      "start": "15:20",
      "end": "16:50",
      "topic": "Beyond MCP: API-Driven Agentic AI for Verifiable Structural Modeling Workflows",
      "speaker": "ดร. ศิรเดช สุริต & ธนาคม บูรณะพิมพ์",
      "org": "ARCH KU",
      "takeaway": "Beyond MCP: ใช้ Agentic AI ร่วมกับ API ของซอฟต์แวร์วิเคราะห์โครงสร้าง ตั้งแต่สร้างโมเดล วิเคราะห์ผล และตรวจสอบร่วมกับ Human-in-the-loop"
    },
    {
      "id": "C06",
      "room": "TR2",
      "start": "09:00",
      "end": "10:00",
      "topic": "openBIM process to design phase, construction phase and operation phase",
      "speaker": "ดร. อภิวัฑธน์",
      "org": "Nemetschek & Digitech One",
      "takeaway": "ข้อมูลโครงการหนึ่งชุดต้องเดินทางผ่านหลายทีมและหลายซอฟต์แวร์ ตั้งแต่เริ่มโครงการจนถึงส่งมอบอาคาร หัวข้อนี้แสดงภาพ openBIM process ทั้งเส้นทาง ว่าแต่ละช่วงใช้เครื่องมือประเภทใด เชื่อมต่อกันผ่านมาตรฐานเปิด IFC, BCF และ IDS อย่างไร และตรวจสอบคุณภาพข้อมูลก่อนส่งต่ออย่างไร เพื่อให้ข้อมูลส่งต่อได้โดยไม่ต้องสร้างใหม่และไม่ตกหล่นระหว่างทาง"
    },
    {
      "id": "C07",
      "room": "TR2",
      "start": "10:20",
      "end": "11:20",
      "topic": "How technology & hardware increase qulity of design, construction & handover?",
      "speaker": "Wongsakorn",
      "org": "Sustainable Solution",
      "takeaway": "การใช้เครื่องมือต่างๆและเทคโนโลยีเพื่อเข้ามาช่วยเพิ่มคุณภาพการทำงานในโครงการตั้งแต่ส่วนออกแบบ ก่อสร้าง และส่งมอบงาน ทั้งโครงการใหม่และโครงการปรับปรุงอาคาร\n\nการเพิ่มความแม่นยำในการงานปรับปรุงอาคาร การค้นหารอยร้าวและจุดรั่วไหลของพลังงานในอาคารเก่า การคุมงานก่อสร้างเพื่อให้ผ่าน QAQC ทั้งอาคารที่ก่อสร้างและ digital delivery"
    },
    {
      "id": "C08",
      "room": "TR2",
      "start": "11:20",
      "end": "12:20",
      "topic": "Governing the future of BIM: Building Digital Trust and Responsible AI",
      "speaker": "Wirada Chairungrueang & Teumyos Menarat",
      "org": "BSI",
      "takeaway": "หลักสูตร BIM Qualification ตาม ISO 19650 จะช่วยให้ท่านและทีมเข้าใจการจัดการข้อมูลอาคารอย่างเป็นระบบ ตั้งแต่การวางแผน ออกแบบ ก่อสร้าง ไปจนถึงการส่งมอบงานอย่างมืออาชีพ เหมาะสำหรับองค์กรที่ต้องการยกระดับการทำงาน BIM ให้สอดคล้องกับแนวปฏิบัติสากล และสร้างความเชื่อมั่นให้กับผู้มีส่วนได้ส่วนเสีย"
    },
    {
      "id": "C09",
      "room": "TR2",
      "start": "13:30",
      "end": "15:00",
      "topic": "The Next Frontier of Real Estate: พลิกโฉมการออกแบบและการบริหารสินทรัพย์หลากมิติสู่เป้าหมาย Net Zero",
      "speaker": "อ. ต่าย (พัสกร เนื่องพุกก์)",
      "org": "Form BIM Arkitek",
      "takeaway": "\"เมื่อเป้าหมาย Net Zero 100% ยังไม่มีโครงการใดทำได้สมบูรณ์ ความท้าทายในวันนี้จึงไม่ใช่การรอคอย... แต่คือการก้าวสู่ The Next Frontier of Real Estate เพื่อช่วงชิงรอยต่อแห่งยุคสมัย ผู้ที่สามารถ พลิกโฉมการออกแบบ และบูรณาการข้อมูลสู่ การบริหารสินทรัพย์หลากมิติ ได้อย่างไร้รอยต่อก่อนใคร คือผู้สร้างมาตรฐานใหม่ให้ตลาดแห่งอนาคต\""
    },
    {
      "id": "C10",
      "room": "TR2",
      "start": "15:20",
      "end": "16:50",
      "topic": "AI for Project Development with Autodesk Assistance",
      "speaker": "คุณชาญ โชคชัย",
      "org": "Autodesk",
      "takeaway": "นำเสนอวิสัยทัศน์ของ Autodesk ต่อบทบาทของ AI ในกระบวนการพัฒนาโครงการ พร้อมแนะนำแนวทางการนำ Autodesk AI, Autodesk Assistant และ Automation มาประยุกต์ใช้จริงสำหรับเจ้าของโครงการ เพื่อช่วยตั้งแต่การพัฒนาแนวคิด การวิเคราะห์ทางเลือก การทำงานร่วมกัน ไปจนถึงการเพิ่มประสิทธิภาพในการตัดสินใจตลอดวงจรโครงการ"
    },
    {
      "id": "C11",
      "room": "TR3",
      "start": "09:00",
      "end": "10:00",
      "topic": "From BIM TOR to Deliverables",
      "speaker": "คุณติ๊ก (ทศมงคล รุ่งเรือง)",
      "org": "Synnex",
      "takeaway": "วัตถุประสงค์\nเพื่อให้เตรียมการสำหรับการทำ BIM และแนะแนวเกี่ยวกับการเริ่มโปรเจกต์ BIM เพื่อส่งต่อให้กับผู้ที่เกี่ยวข้อง ได้อย่างมีประสิทธิภาพ"
    },
    {
      "id": "C12",
      "room": "TR3",
      "start": "10:20",
      "end": "11:20",
      "topic": "Digital Project Management",
      "speaker": "Vuttiya Santikunaporn & Parkanat Apinatachard",
      "org": "Aurecon",
      "takeaway": "การบรรยายในหัวข้อนี้มุ่งศึกษากระบวนการเคลื่อนย้ายของข้อมูลโครงการ ครอบคลุมตั้งแต่ขั้นตอนการออกแบบ การก่อสร้าง การส่งมอบงาน จนถึงการดำเนินงานและบริหารจัดการ โดยนำเสนอประเด็นปัญหาและความท้าทายที่พบบ่อย ได้แก่ บทบาทและหน้าที่ความรับผิดชอบ ข้อกำหนดตามสัญญา ช่องว่างด้านสมรรถนะการทำงาน การพึ่งพาเอกสารส่งมอบในรูปแบบ 2 มิติ และการเข้ามามีส่วนร่วมที่ล่าช้าของทีมปฏิบัติการ ทั้งนี้ ผู้เข้าร่วมจะได้รับความรู้และความเข้าใจเชิงลึกจากประสบการณ์การทำงานจริงและบทเรียนที่ผ่านมา ในการแปลงข้อมูลโครงการให้เป็นสารสนเทศที่สามารถนำไปปฏิบัติได้จริง เพื่อสนับสนุนการดำเนินงานและการบริหารจัดการทรัพย์สินได้อย่างมีประสิทธิภาพ"
    },
    {
      "id": "C13",
      "room": "TR3",
      "start": "11:20",
      "end": "12:20",
      "topic": "From Problems to Possibilities",
      "speaker": "เมธี ทรัพย์เพิ่ม",
      "org": "Thai Obayashi",
      "takeaway": "การนำปัญหาและความท้าทายที่เกิดขึ้นจริงในการดำเนินโครงการ มาเป็นแรงบันดาลใจในการพัฒนาแนวทางแก้ไขปัญหาเชิงดิจิทัลที่นำไปปฏิบัติได้จริง เพื่อเพิ่มความโปร่งใสและการมองเห็นภาพรวมการทำงาน เสริมสร้างความเป็นมาตรฐาน ความร่วมมือในการทำงาน และประสิทธิภาพการส่งมอบโครงการตลอดวงจรชีวิตงานก่อสร้าง"
    },
    {
      "id": "C14",
      "room": "TR3",
      "start": "13:30",
      "end": "15:00",
      "topic": "Automate Data Pipeline, from BIM to Insights",
      "speaker": "อ. ใหม่ (พัฒนา รัตนนาวาทอง)",
      "org": "Maipatana",
      "takeaway": "แสดงเส้นทางข้อมูลจาก BIM ไปสู่ Dashboard สำหรับผู้บริหารโครงการและ FM โดยใช้ Automation และ AI ช่วยงาน"
    },
    {
      "id": "C15",
      "room": "TR3",
      "start": "15:20",
      "end": "16:50",
      "topic": "SketchUp and AI",
      "speaker": "ศ.ฐิติพัฒน์ ประทานทรัพย์",
      "org": "Digitech One",
      "takeaway": "โลก AI+MCP เติบโตมากในปีนี้ ทำให้ user ทุกคน สามารถเข้าถึงข้อมูลและจัดการข้อมูลได้อย่างไม่น่าเชื่อ แต่ทั้งนี้ user ต้องมี data foundation ที่ดี\n\nการบริหารจัดการโครงการ ที่มีข้อมูลต้นทางเป็น digital ไม่ได้ทำได้โดยมีเพียง model แต่จำเป็นต้องมีข้อมูล (data) ที่เหมาะสมกับกระบวนการเหล่านั้น การจัดการข้อมูลเหล่านั้น จำเป็นที่จะต้องเข้าใจวิธีการของแต่ละ software รวมไปถึงรหัสมาตรฐานต่างๆ ประกอบกับการมาของ AI technology และ MCP (Model Context Protocol) ที่มีผลกระทบต่อกระบวนการทำงานเดิมเป็นอย่างมาก มาดูว่าเราจะใช้ข้อมูลและ AI ร่วมกันอย่างไร กรณีตัวอย่าง การจัดการข้อมูลใน SketchUp การบริหารจัดการข้อมูล, data standard, data embedding และ MCP ที่ใช้ได้กับ SketchUp, Revit, AutoCAD และ ArchiCAD ที่จะจะพลิกโฉมการทำงานในปัจจุบัน"
    }
  ]
};
